### ISSUE TITLE
TCP Transport ?

### ISSUE THREAD

**Issue by asafyish** [GraftJS/jschan#35]
Hi,

Is there a plan for a TCP transport ?
I guess that it will have the highest throughput on local network, which is where jschan is going to be used anyway.

**Comment by mcollina** [comment]
Hi! This should already be implemented, it's the https://github.com/GraftJS/jschan#streamSession which can run on top of any stream.

**Comment by asafyish** [comment]
Hi,
Yeah I see I missed it :(
